[package]
name = "polkadot-network-bridge"
version = "0.9.36"
edition = "2021"

[dependencies]
always-assert = "0.1"
async-trait = "0.1.57"
futures = "0.3.21"
gum = { package = "tracing-gum", path = "../../gum" }
polkadot-primitives = { path = "../../../primitives2" }
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["derive"] }
sc-network = { version = "0.10.0-dev", path = "../../../client/network" }
sc-network-common = { version = "0.10.0-dev", path = "../../../client/network/common"}
sp-consensus = {  version = "0.10.0-dev", path = "../../../primitives/consensus/common" }
polkadot-node-subsystem = {path = "../../subsystem" }
polkadot-overseer = { path = "../../overseer" }
polkadot-node-network-protocol = { path = "../protocol" }
polkadot-node-subsystem-util = { path = "../../subsystem-util"}
parking_lot = "0.12.0"
bytes = "1"
fatality = "0.0.6"
thiserror = "1"

[dev-dependencies]
assert_matches = "1.4.0"
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-core = { version = "7.0.0", path = "../../../primitives/core" }
sp-keyring = { version = "7.0.0", path = "../../../primitives/keyring" }
futures-timer = "3"
polkadot-primitives-test-helpers = { path = "../../../primitives2/test-helpers" }
