[package]
name = "test-parachain-halt"
description = "Test parachain which executes forever"
build = "build.rs"
version = "0.9.36"
edition = "2021"

[dependencies]

[build-dependencies]
substrate-wasm-builder = { version = "5.0.0-dev", path = "../../../utils/wasm-builder" }
[features]
default = [ "std" ]
std = []
