[package]
name = "polkadot-gossip-support"
version = "0.9.36"
edition = "2021"

[dependencies]
sp-application-crypto = {version = "7.0.0", path = "../../../primitives/application-crypto" }
sp-keystore = { version = "0.13.0", path = "../../../primitives/keystore" }
sp-core = {  version = "7.0.0", path = "../../../primitives/core"}
sc-network = { version = "0.10.0-dev", path = "../../../client/network" }

polkadot-node-network-protocol = { path = "../protocol" }
polkadot-node-subsystem = { path = "../../subsystem" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }
polkadot-primitives = { path = "../../../primitives2" }

futures = "0.3.21"
futures-timer = "3.0.2"
rand = { version = "0.8.5", default-features = false }
rand_chacha = { version = "0.3.1", default-features = false }
gum = { package = "tracing-gum", path = "../../gum" }

[dev-dependencies]
sp-keyring = { version = "7.0.0", path = "../../../primitives/keyring" }
sp-consensus-babe = { version = "0.10.0-dev", path = "../../../primitives/consensus/babe" }
sp-tracing = {  version = "6.0.0", path = "../../../primitives/tracing" }
sp-authority-discovery = {version = "4.0.0-dev", path = "../../../primitives/authority-discovery" }

polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }

assert_matches = "1.4.0"
async-trait = "0.1.57"
lazy_static = "1.4.0"
