[package]
name = "polkadot-node-core-parachains-inherent"
version = "0.9.36"
edition = "2021"

[dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
gum = { package = "tracing-gum", path = "../../gum" }
thiserror = "1.0.31"
async-trait = "0.1.57"
polkadot-node-subsystem = { path = "../../subsystem" }
polkadot-overseer = { path = "../../overseer" }
polkadot-primitives = { path = "../../../primitives2" }
sp-blockchain = { version = "4.0.0-dev", path = "../../../primitives/blockchain" }
sp-inherents = { version = "4.0.0-dev", path = "../../../primitives/inherents" }
sp-runtime = {  version = "7.0.0", path = "../../../primitives/runtime"  }
