[package]
name = "slot-range-helper"
version = "0.9.36"
edition = "2021"

[dependencies]
paste = "1.0"
enumn = "0.1.5"
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["derive"] }
sp-std = { package = "sp-std",version = "5.0.0", default-features = false, path = "../../../primitives/std" }
sp-runtime = { version = "7.0.0", default-features = false, path = "../../../primitives/runtime" }

[features]
default = ["std"]
std = [
	"sp-std/std",
	"parity-scale-codec/std",
	"sp-runtime/std",
]
