[package]
name = "xcm-executor-integration-tests"
description = "Integration tests for the XCM Executor"
version = "0.9.36"
edition = "2021"

[dependencies]
frame-support = { version = "4.0.0-dev", default-features = false, path = "../../../frame/support" }
frame-system = { version = "4.0.0-dev", path = "../../../frame/system" }
futures = "0.3.21"
pallet-xcm = { path = "../../pallet-xcm" }
polkadot-test-client = { path = "../../../node/test/client" }
polkadot-test-runtime = { path = "../../../runtime2/test-runtime" }
polkadot-test-service = { path = "../../../node/test/service" }
sp-consensus = { version = "0.10.0-dev", path = "../../../primitives/consensus/common", default-features = false}
sp-keyring = { version = "7.0.0", path = "../../../primitives/keyring", default-features = false }
sp-runtime = { version = "7.0.0", default-features = false, path = "../../../primitives/runtime" }
sp-state-machine = { version = "0.13.0", path = "../../../primitives/state-machine" }
xcm = { path = "../..", default-features = false }
xcm-executor = { path = ".." }
sp-tracing = {  version = "6.0.0", path = "../../../primitives/tracing" }

[features]
default = ["std"]
std = [
	"xcm/std",
	"sp-runtime/std",
	"frame-support/std",
]
