[package]
name = "polkadot-node-core-bitfield-signing"
version = "0.9.36"
edition = "2021"

[dependencies]
futures = "0.3.21"
gum = { package = "tracing-gum", path = "../../gum" }
polkadot-primitives = { path = "../../../primitives2" }
polkadot-node-subsystem = { path = "../../subsystem" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }
sp-keystore = { version = "0.13.0", path = "../../../primitives/keystore" }
wasm-timer = "0.2.5"
thiserror = "1.0.31"

[dev-dependencies]
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
test-helpers = { package = "polkadot-primitives-test-helpers", path = "../../../primitives2/test-helpers" }
