[package]
name = "polkadot-node-core-chain-selection"
description = "Chain Selection Subsystem"
version = "0.9.36"
edition = "2021"

[dependencies]
futures = "0.3.21"
futures-timer = "3"
gum = { package = "tracing-gum", path = "../../gum" }
polkadot-primitives = { path = "../../../primitives2" }
polkadot-node-primitives = { path = "../../primitives" }
polkadot-node-subsystem = { path = "../../subsystem" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }
kvdb = "0.13.0"
thiserror = "1.0.31"
parity-scale-codec = "3.1.5"

[dev-dependencies]
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-core = { version = "7.0.0", path = "../../../primitives/core" }
parking_lot = "0.12.0"
assert_matches = "1"
kvdb-memorydb = "0.13.0"
