[package]
name = "polkadot-approval-distribution"
version = "0.9.36"
edition = "2021"

[dependencies]
polkadot-node-primitives = { path = "../../primitives" }
polkadot-node-network-protocol = { path = "../protocol" }
polkadot-node-subsystem = { path = "../../subsystem" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }
polkadot-primitives = { path = "../../../primitives2" }
rand = "0.8"

futures = "0.3.21"
gum = { package = "tracing-gum", path = "../../gum" }

[dev-dependencies]
sp-authority-discovery = {version = "4.0.0-dev", path = "../../../primitives/authority-discovery" }
sp-core = { version = "7.0.0", path = "../../../primitives/core", features = ["std"]  }

polkadot-node-subsystem-util = { path = "../../subsystem-util" }
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
polkadot-primitives-test-helpers = { path = "../../../primitives2/test-helpers" }

assert_matches = "1.4.0"
schnorrkel = { version = "0.9.1", default-features = false }
rand_core = "0.5.1" # should match schnorrkel
rand_chacha = "0.3.1"
env_logger = "0.9.0"
log = "0.4.17"
