[package]
name = "polkadot-collator-protocol"
version = "0.9.36"
edition = "2021"
[dependencies]
always-assert = "0.1.2"
bitvec = { version = "1.0.1", default-features = false, features = ["alloc"] }
futures = "0.3.21"
futures-timer = "3"
gum = { package = "tracing-gum", path = "../../gum" }

sp-core = { version = "7.0.0", path = "../../../primitives/core"}
sp-runtime = {  version = "7.0.0", path = "../../../primitives/runtime" }
sp-keystore = {  version = "0.13.0", path = "../../../primitives/keystore" }

polkadot-primitives = { path = "../../../primitives2" }
polkadot-node-network-protocol = { path = "../../network/protocol" }
polkadot-node-primitives = { path = "../../primitives" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }
polkadot-node-subsystem = {path = "../../subsystem" }
fatality = "0.0.6"
thiserror = "1.0.31"

[dev-dependencies]
log = "0.4.17"
env_logger = "0.9.0"
assert_matches = "1.4.0"
sp-core = { version = "7.0.0", features = ["std"], path = "../../../primitives/core" }
sp-keyring = { version = "7.0.0", path = "../../../primitives/keyring" }
sc-network = { version = "0.10.0-dev", path = "../../../client/network" }
parity-scale-codec = { version = "3.1.5", features = ["std"] }

polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
polkadot-primitives-test-helpers = { path = "../../../primitives2/test-helpers" }
