[package]
name = "polkadot-node-core-av-store"
version = "0.9.36"
edition = "2021"

[dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
kvdb = "0.13.0"
thiserror = "1.0.31"
gum = { package = "tracing-gum", path = "../../gum" }
bitvec = "1.0.0"

parity-scale-codec = { version = "3.1.5", features = ["derive"] }
erasure = { package = "polkadot-erasure-coding", path = "../../../erasure-coding" }
polkadot-node-subsystem = {path = "../../subsystem" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }
polkadot-overseer = { path = "../../overseer" }
polkadot-primitives = { path = "../../../primitives2" }
polkadot-node-primitives = { path = "../../primitives" }

[dev-dependencies]
log = "0.4.17"
env_logger = "0.9.0"
assert_matches = "1.4.0"
kvdb-memorydb = "0.13.0"

sp-core = { version = "7.0.0", path = "../../../primitives/core" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-keyring = { version = "7.0.0", path = "../../../primitives/keyring" }
parking_lot = "0.12.0"
test-helpers = { package = "polkadot-primitives-test-helpers", path = "../../../primitives2/test-helpers" }
