[package]
name = "test-parachain-adder-collator"
description = "Collator for the adder test parachain"
version = "0.9.36"
edition = "2021"
[[bin]]
name = "adder-collator"
path = "src/main.rs"

[[bin]]
name = "adder_collator_puppet_worker"
path = "bin/puppet_worker.rs"

[dependencies]
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["derive"] }
clap = { version = "4.0.9", features = ["derive"] }
futures = "0.3.21"
futures-timer = "3.0.2"
log = "0.4.17"

test-parachain-adder = { path = ".." }
polkadot-primitives = { path = "../../../../primitives2" }
polkadot-cli = { path = "../../../../cli" }
polkadot-service = { path = "../../../../node/service", features = [] }
polkadot-node-primitives = { path = "../../../../node/primitives" }
polkadot-node-subsystem = { path = "../../../../node/subsystem" }

sc-cli = { version = "0.10.0-dev", path = "../../../../client/cli" }
sp-core = { version = "7.0.0", path = "../../../../primitives/core" }
sc-service = { version = "0.10.0-dev", path = "../../../../client/service" }

# This one is tricky. Even though it is not used directly by the collator, we still need it for the
# `puppet_worker` binary, which is required for the integration test. However, this shouldn't be
# a big problem since it is used transitively anyway.
polkadot-node-core-pvf = { path = "../../../../node/core/pvf" }

[dev-dependencies]
polkadot-parachain = { path = "../../.." }
polkadot-test-service = { path = "../../../../node/test/service" }

substrate-test-utils = { version = "4.0.0-dev", path = "../../../../frame/test-utils" }
sc-service = { version = "0.10.0-dev", path = "../../../../client/service" }
sp-keyring = { version = "7.0.0", path = "../../../../primitives/keyring" }
tokio = { version = "1.22.0", features = ["macros"] }
