[package]
name = "polkadot-node-network-protocol"
version = "0.9.36"
edition = "2021"
description = "Primitives types for the Node-side"

[dependencies]
async-trait = "0.1.57"
hex = "0.4.3"
polkadot-primitives = { path = "../../../primitives2" }
polkadot-node-primitives = { path = "../../primitives" }
polkadot-node-jaeger = { path = "../../jaeger" }
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["derive"] }
sc-network = { version = "0.10.0-dev", path = "../../../client/network"  }
sc-network-common = { version = "0.10.0-dev", path = "../../../client/network/common"  }
sc-authority-discovery = { version = "0.10.0-dev", path = "../../../client/authority-discovery" }
strum = { version = "0.24", features = ["derive"] }
futures = "0.3.21"
thiserror = "1.0.31"
fatality = "0.0.6"
rand = "0.8"
derive_more = "0.99"
gum = { package = "tracing-gum", path = "../../gum" }

[dev-dependencies]
rand_chacha = "0.3.1"
