[package]
name = "polkadot-node-core-dispute-coordinator"
version = "0.9.36"
edition = "2021"
[dependencies]
futures = "0.3.21"
gum = { package = "tracing-gum", path = "../../gum" }
parity-scale-codec = "3.1.5"
kvdb = "0.13.0"
thiserror = "1.0.31"
lru = "0.8.0"
fatality = "0.0.6"

polkadot-primitives = { path = "../../../primitives2" }
polkadot-node-primitives = { path = "../../primitives" }
polkadot-node-subsystem = { path = "../../subsystem" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }

sc-keystore = { version = "4.0.0-dev", path = "../../../client/keystore"}


[dev-dependencies]
kvdb-memorydb = "0.13.0"
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-keyring = {ersion = "7.0.0", path = "../../../primitives/keyring" }
sp-core = { version = "7.0.0", path = "../../../primitives/core"  }
sp-keystore = { version = "0.13.0", path = "../../../primitives/keystore"  }
assert_matches = "1.4.0"
test-helpers = { package = "polkadot-primitives-test-helpers", path = "../../../primitives2/test-helpers" }
futures-timer = "3.0.2"
sp-application-crypto = { version = "7.0.0", path = "../../../primitives/application-crypto"  }

[features]
# If not enabled, the dispute coordinator will do nothing.
disputes = []
