[package]
name = "polkadot-availability-bitfield-distribution"
version = "0.9.36"
edition = "2021"

[dependencies]
futures = "0.3.21"
gum = { package = "tracing-gum", path = "../../gum" }
polkadot-primitives = { path = "../../../primitives2" }
polkadot-node-subsystem = {path = "../../subsystem" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }
polkadot-node-network-protocol = { path = "../../network/protocol" }
rand = "0.8"

[dev-dependencies]
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
bitvec = { version = "1.0.0", default-features = false, features = ["alloc"] }
sp-core = {  version = "7.0.0", path = "../../../primitives/core" }
sp-application-crypto = { version = "7.0.0", path = "../../../primitives/application-crypto" }
sp-authority-discovery = {version = "4.0.0-dev", path = "../../../primitives/authority-discovery" }
sp-keystore = { version = "0.13.0", path = "../../../primitives/keystore" }
sp-keyring = { version = "7.0.0", path = "../../../primitives/keyring" }
maplit = "1.0.2"
log = "0.4.17"
env_logger = "0.9.0"
assert_matches = "1.4.0"
rand_chacha = "0.3.1"
