[package]
name = "test-runtime-constants"
version = "0.9.36"
edition = "2021"

[dependencies]
smallvec = "1.8.0"

frame-support = { version = "4.0.0-dev", default-features = false, path = "../../../frame/support" }
primitives = { package = "polkadot-primitives", path = "../../../primitives2", default-features = false }
runtime-common = { package = "polkadot-runtime-common", path = "../../common", default-features = false }
sp-runtime = { version = "7.0.0", default-features = false, path = "../../../primitives/runtime" }
sp-weights = { version = "4.0.0", default-features = false, path = "../../../primitives/weights" }
sp-core = { version = "7.0.0", default-features = false ,path = "../../../primitives/core" }

[features]
default = ["std"]
std = [
	"sp-core/std",
	"sp-runtime/std",
	"sp-weights/std"
]
